recipe: default.v1
language: en
pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    model_group: rasa_command_generation_model
  flow_retrieval:
    active: false

policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
  llm:  # The model for response generation
    model_group: enterprise_search_generation
  embeddings: # The model for your embeddings
    model_group: enterprise_search_embeddings
  vector_store:
    type: "faiss"
    source: "./docs" 
assistant_id: 20250613-141338-all-sharp
