recipe: default.v1
language: en
assistant_id: your-assistant-id

pipeline:
# - name: SingleStepLLMCommandGenerator
#   llm:
#     model_group: rasa_command_generation_model
#   flow_retrieval:
#     active: false
- name: CompactLLMCommandGenerator
  llm:
    model_group: azure_llm
  flow_retrieval:
    embeddings:
      model_group: azure_embeddings

policies:
  - name: FlowPolicy
  - name: EnterpriseSearchPolicy
    llm:
      model_group: azure_llm
    embeddings:
      model_group: azure_embeddings
    vector_store:
      type: "faiss"
      source: "./docs"